backbone: resnet50_dafd
transfer_loss_weight: 1
transfer_loss: dafd
mi_lamb: 1
recon_lamb: 1
lmmd_lamb: 1
adv_lamb: 1
dynamic: True
pixel_adv_lamb: 1
lr: 0.01
weight_decay: 1
momentum: 1
lr_scheduler: False
lr_gamma: 1
lr_decay: 1
n_iter_per_epoch: 100
n_epoch: 100
seed: 1
num_workers: 8
